mongodb:
  hostname: easytravel-mongodb
  container_name: mongodb
  image: "dynatrace/easytravel-mongodb"
  ports:
  - 27017:27017
  - 28017:28017

backend:
  hostname: easytravel-backend
  container_name: backend
  image: "dynatrace/easytravel-backend"
  ports:
  - 8091:8080
  links:
  - mongodb
  environment:
    CATALINA_OPTS: "-Dconfig.apmServerDefault=APM -Xmx300m"
    ET_DATABASE_LOCATION: "easytravel-mongodb:27017"
    ET_MONGO_AUTH_DB: "admin"
    ET_DATABASE_USER: "etAdmin"
    ET_DATABASE_PASSWORD: "adminadmin"

frontend:
  hostname: easytravel-frontend
  container_name: frontend
  image: "dynatrace/easytravel-frontend"
  ports:
  - 8080
  links:
  - backend
  - mongodb
  environment:
    CATALINA_OPTS: "-Dconfig.apmServerDefault=APM -Xmx525m"
    ET_BACKEND_URL: "http://easytravel-backend:8080"

angular-frontend:
  hostname: easytravel-angular-frontend
  container_name: angular-frontend
  image: "dynatrace/easytravel-angular-frontend"
  ports:
  - 8080
  links:
  - backend
  - mongodb
  environment:
    CATALINA_OPTS: "-Dconfig.apmServerDefault=APM -Xmx525m"
    ET_BACKEND_URL: "http://easytravel-backend:8080"

www:
  hostname: easytravel-www
  container_name: www
  image: "dynatrace/easytravel-nginx"
  ports:
  - 80:80
  - 9079:9079
  links:
  - frontend
  - angular-frontend
  - backend
  environment:
    ET_FRONTEND_LOCATION: "easytravel-frontend:8080"
    ET_ANGULAR_FRONTEND_LOCATION: "easytravel-angular-frontend:8080"
    ET_BACKEND_LOCATION: "easytravel-backend:8080"

loadgen:
  container_name: loadgen
  image: "dynatrace/easytravel-loadgen"
  links:
  - backend
  - frontend
  - www
  environment:
    ET_FRONTEND_URL: "http://easytravel-www:80"
    ET_BACKEND_URL: "http://easytravel-www:8080"
    #ET_PROBLEMS: "BadCacheSynchronization,CPULoad,DatabaseCleanup,DatabaseSlowdown,FetchSizeTooSmall,JourneySearchError404,JourneySearchError500,LoginProblems,MobileErrors,TravellersOptionBox"
    ET_PROBLEMS: "CPULoadExternalProcess,CPULoadJourneyService,BadCacheSynchronization,CPULoad,JourneySearchError404,SlowAuthentication,SlowImages,SlowUserLogin,WorldMapDNSFailsAsia,JourneySearchError500,DatabaseSlowdown,SlowIoDummyPaymentService,FetchSizeTooSmall,InfiniteLoopInFrontend,DeadlockInFrontend,SmallMemoryLeak,JourneyUpdateSlow,TravellersOptionBox,LoginProblems"
    #ET_PROBLEMS_DELAY: 20
    ET_VISIT_NUMBER: 12


headless-loadgen:
  container_name: headless_loadgen
  image: "dynatrace/easytravel-headless-loadgen"
  links:
  - backend
  - angular-frontend
  - www
  environment:
    ET_ANGULAR_FRONTEND_URL: "http://easytravel-www:9079"
    ET_VISIT_NUMBER: 2
    MAX_CHROME_DRIVERS: 4
    #SCENARIO_NAME: "Headless Angular Scenario"
    ET_PROBLEMS_DELAY: 7500
